name: jakdam_farm_manager
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  fluttertoast: ^8.2.5
  lottie: ^3.1.2
  provider: ^6.1.2
  fl_chart: ^0.68.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launch_icon.jpeg"  # Path to your app icon

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - assets/images/
    - assets/image/

