name: jakdam_farm_manager
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  fluttertoast: ^8.2.10
  lottie: ^3.3.0
  provider: ^6.1.2
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  animate_do: ^3.3.4
  intl: ^0.20.1
  uuid: ^4.5.1
  path_provider: ^2.1.5
  open_file: ^3.5.10
  permission_handler: ^11.3.1
  excel: ^4.0.6
  file_picker: ^8.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - assets/images/
    - assets/image/
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/launch_icon.jpeg
